### ISSUE TITLE
#HK Meetup 3 20170105

### ISSUE THREAD

**Issue by debuggingfuture** [code4hk/showmethecode#11]
## 日期 Date
- 20170105 (TBC)

## 地點 Location
- Hong Kong

## 場地 Venue
OneSky (TBC)

## 題目 Sessions
- webVR with webgl/three.js by Issac
- Elm by @SWTPAIN
- Facebook Bot by Himphen Hui Hau Him
- api.ai in python - Ho Wa Wong
- Speed up R 10x with C++ by Fuk Chan
- 神經網絡鑑別靚女 - Andy Shu Hsin
- 5min on 同态加密 - Python code is Crypto-Geofence - Nick

**Comment by isaacyiu0369** [comment]
我可以講下 [webVR](https://webvr.info) with webgl/three.js 🤔

**Comment by himphen** [comment]
可唔可以講點樣 10 分鐘開發 Facebook Bot 😂

**Comment by debuggingfuture** [comment]
sounds interesting, please! @himphen

**Comment by chainsawriot** [comment]
唔知講呢啲得唔得：

用拙劣的 C++ 加速 R 計算十倍 @chainsawriot

**Comment by kafaichoi** [comment]
I might talk about ~~cycle.js~~ Elm if I have time to prepare

**Comment by blaesus** [comment]
我想講用神經網絡鑑別靚女⋯⋯
No slide s既意思係唔可以用slides定可以唔用？

**Comment by debuggingfuture** [comment]
@andyshuhsin  正!
`No slides` = 唔可以用slides

**Comment by howawong** [comment]
@himphen  will you cover AIaaS ? If not, I just demonstrate api.ai in python.

**Comment by himphen** [comment]
@howawong No

**Comment by SCMHK** [comment]
想黎聽

**Comment by mapmeld** [comment]
If I can do a talk, 5min on [同态加密](https://zh.wikipedia.org/wiki/%E5%90%8C%E6%80%81%E5%8A%A0%E5%AF%86) - Python code is [Crypto-Geofence](https://github.com/Georeactor/crypto-geofence)

**Comment by debuggingfuture** [comment]
sources of webVR https://github.com/ymcatar/webvr-demo

**Comment by debuggingfuture** [comment]
potential next topic: async in Elm by @SWTPAIN

**Comment by debuggingfuture** [comment]
by ho wa
https://github.com/howawong/show_me_the_code_jan_5_demo/blob/master/sample.py

**Comment by debuggingfuture** [comment]
by himphen 

Postback FB messenger
https://developers.facebook.com/docs/messenger-platform/webhook-reference/postback

**Comment by debuggingfuture** [comment]
from Andy
https://github.com/andyshuhsin/neural-gender-demo/blob/master/Neural-Network-LangLui-Classification-Demo.ipynb

Thanks all speakers!

**Comment by chainsawriot** [comment]
http://chainsawriot.github.io/onebigfuckingrmd/#rcpp_應用例
