### ISSUE TITLE
#HK Meetup #4 20170216 @ Oursky

### ISSUE THREAD

**Issue by debuggingfuture** [code4hk/showmethecode#15]
## 日期 Date
- 20170216 (THU)

## 地點 Location
- Hong Kong

## 場地 Venue
- Oursky

## 題目 Sessions
(Assume cantonese)
- Deep Learning: NLP in Past & Now (30min Talk with Slides, by @Joseph) 
- lightning talks
  - "Making Progressive Web App with webpack and firebase" by @tonyhhyip 
  - "how to build a CI/CD pipline" for team across HK & China. by @sunnycmf  
  -  coding for image processing in objective-c by @ tom tong
  - Elm (TBC)

**Comment by kafaichoi** [comment]
I want to share about "Writing widget in Elm". But could I confirm it by the end of this week😂 Not sure I have enough time to prepare.

**Comment by debuggingfuture** [comment]
I will speak on contentful.com if no other speakers

**Comment by sunnycmf** [comment]
I can share "how to build a CI/CD pipline" for team across HK & China.

**Comment by tonyhhyip** [comment]
I want to talk about "Making Progressive Web App with webpack and firebase"

**Comment by tomtomtong** [comment]
This is my company GitHub page https://github.com/spincle
There is an example about custom cifilter.

**Comment by indiejoseph** [comment]
My slide
https://docs.google.com/presentation/d/1_adHIseYqw9dbZzr2m-HC3vZTtxETFJ_aj47tgOgZzc/edit#slide=id.g1c8d0b973a_0_1576
