### ISSUE TITLE
#HK Meetup #5 20170315 @ lifehack

### ISSUE THREAD

**Issue by debuggingfuture** [code4hk/showmethecode#16]
## 日期 Date
- March 15

## 地點 Location
- Hong Kong

## 場地 Venue
- Lifehack

## 題目 Sessions

- lightweight CMS with contentful by @vincentlaucy
- simple datapipeline with luigi by @howawong 
- internal decision boundaries of neural networks by @Cybernetic1 
- Responsive placeholder with CSS by @199911  (lifehack)
- use of Draft.js: a framework for building rich text editors in React. by @mtyiu (lifehack)
- "Drag-less iOS development, Be Confident" by  lo gap

**Comment by debuggingfuture** [comment]
venue will be lifehack 🎉

**Comment by debuggingfuture** [comment]
i will speak on `lightweight CMS with contentful`

https://github.com/code4hk/showmethecode/blob/master/contentful.md

**Comment by vincentlaucy** [comment]
TBC:
speakers
- @howawong 
- @Yan King Yin
- @rogerhokp

**Comment by 199911** [comment]
I can share `Responsive placeholder with CSS`

**Comment by debuggingfuture** [comment]
@Cybernetic1 will speak on `internal decision boundaries of neural networks` 

https://cloud.sagemath.com/projects/125f0d12-2c9b-487c-91a7-0ee67aeb953a/files/linkage-experiment(1).sagews

**Comment by Cybernetic1** [comment]
where is the address of Lifehack?

**Comment by denistsoi** [comment]
"Lifehack HQ 9/F, Tungtex Building 203 Wai Yip Street, Kwun Tong, Kowloon"

**Comment by howawong** [comment]
I will do a quick demo on `simple datapipeline with luigi` .

**Comment by mtyiu** [comment]
I will demonstrate the use of Draft.js: a framework for building rich text editors in React.

**Comment by debuggingfuture** [comment]
nice we have 6 speakers now 🍾 
Anyone else who wanna speak please share next time!

**Comment by gaplo917** [comment]
I will share "Drag-less" iOS Development experience with related sample implementation/pattern (Swift) to achieve:

* all views can always be previewed meaningfully
* less error-prone development cycle
* confident to add/modify/delete code
* mergeable code in git
* nearly zero-learning curve for any new comer in iOS 
* unlash all the useful OOP patterns that are commonly sealed by storyboard & nib
* Strictly decouple all UI related code

**_"Drag-less" mean NO mouse dragging in Xcode_**

**Comment by howawong** [comment]
FYI
https://github.com/howawong/luigi_pipeline_demo

**Comment by mtyiu** [comment]
Repository for the Draft.js Demo: https://github.com/mtyiu/code4hk-draft-js-demo
Live demo page: https://mtyiu.github.io/code4hk-draft-js-demo/
