### ISSUE TITLE
#HK Meetup 20161115

### ISSUE THREAD

**Issue by debuggingfuture** [code4hk/showmethecode#2]
## 日期 Date
20161115

## 地點 Location
- Hong Kong

### Language
-  Cantonese 廣東話 w/ English Slides

## 場地 Venue
- OneSky

## 題目 Sessions
- metaprogramming in elixir @ james
  - under /breaking_meta
- iot with john-five@rogerhokp
  - https://github.com/code4hk/showmethecode/tree/master/Arduino
- serviceworker mock api @ isaac

## Note
- hosted together with javascript@HK meetup, another talk being React Native by @SWTPAIN (ka fai)

**Comment by rogerhokp** [comment]
vue.js @ joseph
serviceworker mock api @ isaac
iot in js @ roger

**Comment by rogerhokp** [comment]
elixir @ james

**Comment by debuggingfuture** [comment]
Let's do one more #3 purely show me the code, and push some into backlog #1?

sounds like everything js anyway

**Comment by rogerhokp** [comment]
So, which topic included in 15/Nov?

**Comment by angusonesky** [comment]
不如咁 ？ 亂吹
RxJS Practical Ajax Example @vincentlaucy 
elixir / rxjs-observable @ james
serviceworker mock api @ isaac

下次 #3 
iot in js @ roger
vue.js @ joseph

**Comment by rogerhokp** [comment]
i m ok

**Comment by debuggingfuture** [comment]
can we wap both rxjs to #3 , with roger/joseph? sounds joseph / roger ready, I'm not lol

**Comment by debuggingfuture** [comment]
I might talk on http://json-schema.org/ / _.conformsTo

**Comment by rogerhokp** [comment]
O james just `elixir`, i update it.
You have 9 days to prepare :so9sad:

**Comment by jamescheuk91** [comment]
@rogerhokp thanks lol
just intro to meta programming in elixir.
Not going to intro the language itself.
9 share lol
