### ISSUE TITLE
#TW Meetup  #1 20170427 @ Emerson's Studio

### ISSUE THREAD

**Issue by debuggingfuture** [code4hk/showmethecode#22]
## 日期 Date
- 27 Apr
## 地點 Location
- Taiwan

## 場地 Venue
- Emerson's Studio
台北市中山區復興北路350號3樓, Taipei 

## 題目 Sessions
- in <<title>> @<<speaker>> , with one-line to describe
- Contentful by @vincentlaucy

**Comment by adrianliaw** [comment]
<Intro to [bulma](https://bulma.io/)> @adrianliaw A modern CSS framework based on Flexbox

**Comment by whosmvp** [comment]
Java array & Bluetooth low energy

**Comment by debuggingfuture** [comment]
@rickmak will talk abt CI setup at [oursky](oursky.com)
