### ISSUE TITLE
#HK Meetup #6 - Topic: F8

### ISSUE THREAD

**Issue by debuggingfuture** [code4hk/showmethecode#23]
## 日期 Date
20170504

## 地點 Location
- Hong Kong

## 場地 Venue
- 01 Space

## 題目 Sessions
- in <<title>> @<<speaker>> , with one-line to describe

**Comment by indiejoseph** [comment]
Brain-typing
Skin-hearing

**Comment by debuggingfuture** [comment]
I will try to watch these more marketing-facing stuff
- https://developers.facebook.com/videos/f8-2017/growth-marketing-best-practices-for-getting-and-keeping-an-audience/
- https://developers.facebook.com/videos/f8-2017/explore-the-power-of-the-pages-api/
- https://developers.facebook.com/videos/f8-2017/the-future-of-monetizing-with-audience-network/
- https://developers.facebook.com/videos/f8-2017/whats-new-with-news-feed/

**Comment by raymundt** [comment]
Facebook Litho - A declarative framework for building efficient UIs on Android

**Comment by bryanleekw** [comment]
great!

**Comment by debuggingfuture** [comment]
note to speaker: only HDMI available, might need to use google hangout if no adapters

**Comment by balling** [comment]
The Evolution of React and GraphQL at Facebook and Beyond

**Comment by isaacyiu0369** [comment]
我溫 final 冇時間 prep，下次啦

**Comment by debuggingfuture** [comment]
@rogerhokp on jest right?

**Comment by rogerhokp** [comment]
@vincentlaucy i m ok, React Fiber / Modern

**Comment by rogerhokp** [comment]
Jest @rogerhokp
