### ISSUE TITLE
#HK Meetup 20161130

### ISSUE THREAD

**Issue by debuggingfuture** [code4hk/showmethecode#3]
## 日期 Date
TBC

## 地點 Location
- Hong Kong / Taiwan

## 場地 Venue
- e.g. OneSky?

## 題目 Sessions
- in <<title>> @<<speaker>> , with one-line to describe

**Comment by debuggingfuture** [comment]
Current Line Up:
- @joseph [intro to vuejs] (https://github.com/code4hk/showmethecode/issues/1#issuecomment-260668910)
- @vincentlaucy Json schema, `adding type to javascript without type systems`
- @gilbertwat [Functional Programming in lodash](https://github.com/code4hk/showmethecode/issues/1#issuecomment-260668464)
- @rogerhokp `flowtype.org`
- @karlvlam Rust in DevOps 
- @jjbubudi Kotlin on Android

**Comment by rogerhokp** [comment]
How many topics needed? 5/6?

**Comment by debuggingfuture** [comment]
prepare 6-7 might be better

**Comment by rogerhokp** [comment]
added me @ flow `flowtype.org`

**Comment by gilbertwat** [comment]
@rogerhokp done

**Comment by debuggingfuture** [comment]
great @rogerhokp  then I will do json schema, adding type to javascript without type system
btw 1-line description

**Comment by rogerhokp** [comment]
@angus will talk ` TYK + auth0  or  TYK vs apigee`

**Comment by rogerhokp** [comment]
`Rust in DevOps` @karlvlam
https://github.com/rust-lang/rust

**Comment by jjbubudi** [comment]
@jjbubudi Kotlin on Android
https://kotlinlang.org/

**Comment by indiejoseph** [comment]
@indiejoseph vue.js https://github.com/indiejoseph/demo-vue

**Comment by karlvlam** [comment]
Rust in DevOps -> https://github.com/karlvlam/ec2ip
