### ISSUE TITLE
#HK BarcampHK 20161210

### ISSUE THREAD

**Issue by debuggingfuture** [code4hk/showmethecode#4]
## 日期 Date
10Dec

## 地點 Location
- Hong Kong

## 場地 Venue
- PolyU CoreV

## 題目 Sessions
- in <<title>> @<<speaker>> , with one-line to describe

## Remarks
Barcamp is unconference anyway, lets plan for a bunch of talks :)

**Comment by debuggingfuture** [comment]
Topics proposing:
- VueJS’s reactivity @vincentlaucy
  - a bit comparison against angular1/reactjs
- a story to refactor a callback hell to FP code in lodash @gilbertwat

**Comment by denistsoi** [comment]
@vincentlaucy  - do you have  slides for this talk?

**Comment by debuggingfuture** [comment]
hey @denistsoi  ! we don't do slides in these talks, but you might chk out the videos in fb group
